baseURL = "https://blog.cyb.re/"
languageCode = "en-us"
title = "CYBRE blog"
theme = "smol-mod"
[menu]
  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3
[markup.goldmark.renderer]
  unsafe= true